"""Reconstruction-based grid detection via latent-variable optimization.

Models the image as generated by an underlying pixel grid with per-cell colors,
rendered with anti-aliasing. Finds the grid parameters (step size, offsets) that
minimize reconstruction error — the difference between the observed image and
the ideal grid rendering.

This approach avoids the information loss of 1D gradient projection and the
chicken-and-egg problem of quantize-then-detect, because it operates directly
on the original image pixels in 2D.
"""
from __future__ import annotations

import logging
from typing import List, Optional, Tuple

import numpy as np
from PIL import Image

from .config import Config

logger = logging.getLogger("pixel_snapper")

# Import the canonical Candidate type from candidates module to avoid duplication.
# Deferred import in functions that need it to avoid circular imports.


# ---------------------------------------------------------------------------
# Integral image helpers
# ---------------------------------------------------------------------------

def _build_integral_images(
    arr: np.ndarray, mask: np.ndarray
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Build integral images for fast rectangular sum queries.

    Args:
        arr: Image array of shape (H, W, C) as float64.
        mask: Boolean array of shape (H, W), True for opaque pixels.

    Returns:
        Tuple of (integral_sum, integral_sq, integral_count) where:
        - integral_sum[c, y, x] = sum of channel c values in [0..y-1, 0..x-1]
        - integral_sq[c, y, x] = sum of squared channel c values
        - integral_count[y, x] = count of opaque pixels
        All have shape (C, H+1, W+1) or (H+1, W+1) with a zero-padded border.
    """
    h, w, c = arr.shape

    # Mask out transparent pixels
    masked = arr * mask[:, :, np.newaxis]
    masked_sq = masked * masked

    # Transpose to (C, H, W) for per-channel integral images
    masked_chw = masked.transpose(2, 0, 1)
    masked_sq_chw = masked_sq.transpose(2, 0, 1)

    # Build integral images with zero-padded border
    integral_sum = np.zeros((c, h + 1, w + 1), dtype=np.float64)
    integral_sq = np.zeros((c, h + 1, w + 1), dtype=np.float64)
    integral_count = np.zeros((h + 1, w + 1), dtype=np.float64)

    integral_sum[:, 1:, 1:] = np.cumsum(np.cumsum(masked_chw, axis=1), axis=2)
    integral_sq[:, 1:, 1:] = np.cumsum(np.cumsum(masked_sq_chw, axis=1), axis=2)
    mask_f = mask.astype(np.float64)
    integral_count[1:, 1:] = np.cumsum(np.cumsum(mask_f, axis=0), axis=1)

    return integral_sum, integral_sq, integral_count


def _rect_query(
    integral: np.ndarray, y0: int, x0: int, y1: int, x1: int
) -> np.ndarray:
    """Query a rectangular region from an integral image.

    Args:
        integral: Integral image of shape (C, H+1, W+1) or (H+1, W+1).
        y0, x0: Top-left corner (inclusive, in original coords).
        y1, x1: Bottom-right corner (exclusive, in original coords).

    Returns:
        Sum over the rectangle, shape (C,) or scalar.
    """
    # Integral image is 1-indexed (shifted by 1)
    return (
        integral[..., y1, x1]
        - integral[..., y0, x1]
        - integral[..., y1, x0]
        + integral[..., y0, x0]
    )


# ---------------------------------------------------------------------------
# Reconstruction error computation
# ---------------------------------------------------------------------------

def _compute_reconstruction_error(
    integral_sum: np.ndarray,
    integral_sq: np.ndarray,
    integral_count: np.ndarray,
    col_cuts: List[int],
    row_cuts: List[int],
    width: int = 0,
    height: int = 0,
) -> float:
    """Compute normalized reconstruction error with parsimony penalty.

    For each cell, the optimal representative color is the mean, and the
    reconstruction error is the sum of squared deviations from that mean
    (i.e., the variance * count). This equals: sum(x^2) - sum(x)^2 / n.

    To avoid sub-multiples of the true step winning (e.g., step=4 on an 8px
    grid), we add a parsimony penalty proportional to the fraction of total
    variance "explained" by the grid, scaled by log(num_cells). This is
    analogous to BIC/MDL in model selection — prefer simpler models unless
    the data strongly favors more parameters.

    Args:
        integral_sum: Integral sum image, shape (C, H+1, W+1).
        integral_sq: Integral squared image, shape (C, H+1, W+1).
        integral_count: Integral count image, shape (H+1, W+1).
        col_cuts: Column boundaries.
        row_cuts: Row boundaries.
        width: Image width (for total variance normalization).
        height: Image height (for total variance normalization).

    Returns:
        Penalized reconstruction error (lower is better).
    """
    total_error = 0.0

    for j in range(len(row_cuts) - 1):
        y0, y1 = row_cuts[j], row_cuts[j + 1]
        if y1 <= y0:
            continue
        for i in range(len(col_cuts) - 1):
            x0, x1 = col_cuts[i], col_cuts[i + 1]
            if x1 <= x0:
                continue

            count = _rect_query(integral_count, y0, x0, y1, x1)
            if count < 1.0:
                continue

            # Per-channel: sum(x^2) - sum(x)^2 / n
            s = _rect_query(integral_sum, y0, x0, y1, x1)   # shape (C,)
            sq = _rect_query(integral_sq, y0, x0, y1, x1)    # shape (C,)
            cell_error = np.sum(sq - (s * s) / count)
            total_error += cell_error

    # Compute total image variance for normalization
    h_lim = height if height > 0 else (integral_count.shape[0] - 1)
    w_lim = width if width > 0 else (integral_count.shape[1] - 1)
    total_pixels = _rect_query(integral_count, 0, 0, h_lim, w_lim)

    if total_pixels < 1.0:
        return float("inf")

    # Total image variance (the "null model" with 1 cell)
    total_s = _rect_query(integral_sum, 0, 0, h_lim, w_lim)
    total_sq = _rect_query(integral_sq, 0, 0, h_lim, w_lim)
    total_variance = float(np.sum(total_sq - (total_s * total_s) / total_pixels))

    if total_variance < 1e-10:
        return 0.0

    # Fraction of variance remaining (0 = perfect fit, 1 = no improvement)
    residual_fraction = total_error / total_variance

    # AIC-inspired parsimony penalty: 2K/N where K = 3 * num_cells (each cell
    # has 3 color parameters) and N = total pixels. This penalizes model
    # complexity in proportion to the data size, preventing over-fitting to
    # sub-pixel noise. The factor of 2 follows AIC convention.
    num_cells = max((len(col_cuts) - 1) * (len(row_cuts) - 1), 1)
    num_params = 3 * num_cells
    aic_penalty = 2.0 * num_params / total_pixels

    return residual_fraction + aic_penalty


def _make_uniform_cuts(step: float, offset: float, limit: int) -> List[int]:
    """Generate uniform grid cuts for a given step and offset.

    Args:
        step: Cell size.
        offset: Starting offset.
        limit: Image dimension.

    Returns:
        Sorted list of cut positions including 0 and limit.
    """
    cuts = set()
    cuts.add(0)
    cuts.add(limit)

    pos = offset
    while pos < limit:
        c = int(round(pos))
        if 0 < c < limit:
            cuts.add(c)
        pos += step

    return sorted(cuts)


# ---------------------------------------------------------------------------
# Phase 1: Coarse grid search
# ---------------------------------------------------------------------------

def _coarse_grid_search(
    integral_sum: np.ndarray,
    integral_sq: np.ndarray,
    integral_count: np.ndarray,
    width: int,
    height: int,
    min_step: int,
    max_step: int,
    offset_stride: int = 1,
    resolution_hint: Optional[int] = None,
) -> List[Tuple[float, float, float, float]]:
    """Search over step sizes and offsets to find best grid parameters.

    Args:
        integral_sum: Integral sum image.
        integral_sq: Integral squared image.
        integral_count: Integral count image.
        width: Image width.
        height: Image height.
        min_step: Minimum step size to search.
        max_step: Maximum step size to search.
        offset_stride: Stride for offset search (1 = every pixel, 2 = every other).
        resolution_hint: If set, only consider steps yielding <= this many cells.

    Returns:
        List of (error, step, offset_x, offset_y) tuples sorted by error.
    """
    results: List[Tuple[float, float, float, float]] = []

    for step in range(min_step, max_step + 1):
        # Skip steps that would produce too many cells
        if resolution_hint is not None:
            cells_x = len(_make_uniform_cuts(float(step), 0.0, width)) - 1
            cells_y = len(_make_uniform_cuts(float(step), 0.0, height)) - 1
            if max(cells_x, cells_y) > resolution_hint:
                continue

        # Determine offset search range
        max_offset = min(step, 8)  # Cap offset search to keep things fast
        stride = max(1, offset_stride)

        best_error_for_step = float("inf")
        best_ox, best_oy = 0.0, 0.0

        for ox in range(0, max_offset, stride):
            col_cuts = _make_uniform_cuts(float(step), float(ox), width)
            for oy in range(0, max_offset, stride):
                row_cuts = _make_uniform_cuts(float(step), float(oy), height)

                error = _compute_reconstruction_error(
                    integral_sum, integral_sq, integral_count,
                    col_cuts, row_cuts, width, height,
                )

                if error < best_error_for_step:
                    best_error_for_step = error
                    best_ox, best_oy = float(ox), float(oy)

        results.append((best_error_for_step, float(step), best_ox, best_oy))

    results.sort(key=lambda x: x[0])
    return results


# ---------------------------------------------------------------------------
# Phase 2: Sub-pixel refinement
# ---------------------------------------------------------------------------

def _refine_grid_nelder_mead(
    integral_sum: np.ndarray,
    integral_sq: np.ndarray,
    integral_count: np.ndarray,
    width: int,
    height: int,
    initial_step: float,
    initial_ox: float,
    initial_oy: float,
    max_iterations: int = 60,
) -> Tuple[float, float, float, float]:
    """Refine grid parameters using Nelder-Mead simplex optimization.

    Optimizes (step, offset_x, offset_y) to minimize reconstruction error.
    Implemented directly to avoid scipy dependency.

    Args:
        integral_sum: Integral sum image.
        integral_sq: Integral squared image.
        integral_count: Integral count image.
        width: Image width.
        height: Image height.
        initial_step: Starting step size.
        initial_ox: Starting X offset.
        initial_oy: Starting Y offset.
        max_iterations: Maximum optimization iterations.

    Returns:
        (error, step, offset_x, offset_y) for the best found parameters.
    """
    total_pixels = _rect_query(integral_count, 0, 0, height, width)
    if total_pixels < 1:
        return float("inf"), initial_step, initial_ox, initial_oy

    def objective(params: np.ndarray) -> float:
        s, ox, oy = params
        if s < 3.0:
            return float("inf")
        # Clamp offsets to [0, step)
        ox = ox % s
        oy = oy % s
        col_cuts = _make_uniform_cuts(s, ox, width)
        row_cuts = _make_uniform_cuts(s, oy, height)
        return _compute_reconstruction_error(
            integral_sum, integral_sq, integral_count,
            col_cuts, row_cuts, width, height,
        )

    # Initialize simplex around the starting point
    x0 = np.array([initial_step, initial_ox, initial_oy], dtype=np.float64)
    n = len(x0)
    # Perturbation sizes: step ±0.5, offsets ±1.0
    perturbations = np.array([0.5, 1.0, 1.0])

    simplex = np.zeros((n + 1, n))
    simplex[0] = x0
    for i in range(n):
        vertex = x0.copy()
        vertex[i] += perturbations[i]
        simplex[i + 1] = vertex

    # Evaluate all vertices
    f_values = np.array([objective(v) for v in simplex])

    # Standard Nelder-Mead coefficients
    alpha = 1.0   # reflection
    gamma = 2.0   # expansion
    rho = 0.5     # contraction
    sigma = 0.5   # shrink

    for _ in range(max_iterations):
        # Sort vertices
        order = np.argsort(f_values)
        simplex = simplex[order]
        f_values = f_values[order]

        # Check convergence
        if np.max(np.abs(f_values - f_values[0])) < 1e-8:
            break
        if np.max(np.abs(simplex[-1] - simplex[0])) < 1e-6:
            break

        # Centroid of all points except worst
        centroid = simplex[:-1].mean(axis=0)

        # Reflection
        xr = centroid + alpha * (centroid - simplex[-1])
        fr = objective(xr)

        if f_values[0] <= fr < f_values[-2]:
            simplex[-1] = xr
            f_values[-1] = fr
            continue

        # Expansion
        if fr < f_values[0]:
            xe = centroid + gamma * (xr - centroid)
            fe = objective(xe)
            if fe < fr:
                simplex[-1] = xe
                f_values[-1] = fe
            else:
                simplex[-1] = xr
                f_values[-1] = fr
            continue

        # Contraction
        xc = centroid + rho * (simplex[-1] - centroid)
        fc = objective(xc)
        if fc < f_values[-1]:
            simplex[-1] = xc
            f_values[-1] = fc
            continue

        # Shrink
        for i in range(1, n + 1):
            simplex[i] = simplex[0] + sigma * (simplex[i] - simplex[0])
            f_values[i] = objective(simplex[i])

    best_idx = np.argmin(f_values)
    best = simplex[best_idx]
    best_s = best[0]
    best_ox = best[1] % best_s if best_s > 0 else 0.0
    best_oy = best[2] % best_s if best_s > 0 else 0.0

    return float(f_values[best_idx]), float(best_s), float(best_ox), float(best_oy)


# ---------------------------------------------------------------------------
# Phase 3: Non-uniform grid correction
# ---------------------------------------------------------------------------

def _local_grid_correction(
    integral_sum: np.ndarray,
    integral_sq: np.ndarray,
    integral_count: np.ndarray,
    cuts: List[int],
    limit: int,
    search_radius: int = 2,
    is_cols: bool = True,
    other_cuts: Optional[List[int]] = None,
) -> List[int]:
    """Locally adjust each grid boundary to minimize cell variance.

    For each interior cut, test positions within ±search_radius pixels and
    keep the one that minimizes the combined variance of the two adjacent cells.

    Args:
        integral_sum: Integral sum image, shape (C, H+1, W+1).
        integral_sq: Integral squared image.
        integral_count: Integral count image.
        cuts: Current cut positions along this axis.
        limit: Image dimension along this axis.
        search_radius: Pixels to search in each direction.
        is_cols: True if adjusting column cuts, False for row cuts.
        other_cuts: Cut positions along the other axis (for cell bounds).

    Returns:
        Adjusted list of cut positions.
    """
    if other_cuts is None or len(other_cuts) < 2 or len(cuts) < 3:
        return cuts

    adjusted = list(cuts)

    for idx in range(1, len(cuts) - 1):
        prev_cut = adjusted[idx - 1]
        next_cut = cuts[min(idx + 1, len(cuts) - 1)]
        current = cuts[idx]

        lo = max(prev_cut + 1, current - search_radius)
        hi = min(next_cut - 1, current + search_radius)

        if lo > hi:
            continue

        best_error = float("inf")
        best_pos = current

        for pos in range(lo, hi + 1):
            error = 0.0
            for j in range(len(other_cuts) - 1):
                oy0 = other_cuts[j]
                oy1 = other_cuts[j + 1]
                if oy1 <= oy0:
                    continue

                # Two cells: [prev_cut..pos] and [pos..next_cut]
                for x0, x1 in [(prev_cut, pos), (pos, next_cut)]:
                    if x1 <= x0:
                        continue

                    if is_cols:
                        cy0, cx0, cy1, cx1 = oy0, x0, oy1, x1
                    else:
                        cy0, cx0, cy1, cx1 = x0, oy0, x1, oy1

                    count = _rect_query(integral_count, cy0, cx0, cy1, cx1)
                    if count < 1.0:
                        continue

                    s = _rect_query(integral_sum, cy0, cx0, cy1, cx1)
                    sq = _rect_query(integral_sq, cy0, cx0, cy1, cx1)
                    error += float(np.sum(sq - (s * s) / count))

            if error < best_error:
                best_error = error
                best_pos = pos

        adjusted[idx] = best_pos

    return adjusted


# ---------------------------------------------------------------------------
# LAB conversion for perceptual error
# ---------------------------------------------------------------------------

def _rgb_to_approx_lab(arr: np.ndarray) -> np.ndarray:
    """Convert RGB uint8 array to approximate LAB for perceptual error.

    Uses a fast linear approximation that avoids the full sRGB gamma/XYZ
    pipeline. The approximation is: L ≈ 0.2126R + 0.7152G + 0.0722B (luminance),
    a ≈ R - G, b ≈ 0.5*(R + G) - B. This orders errors perceptually better
    than raw RGB while staying very fast.

    Args:
        arr: Image array of shape (H, W, 3) or (H, W, 4), uint8.

    Returns:
        Array of shape (H, W, 3), float64, in approximate perceptual space.
    """
    rgb = arr[:, :, :3].astype(np.float64)
    r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]

    # Perceptual-ish opponent color space (fast, no gamma)
    l_chan = 0.2126 * r + 0.7152 * g + 0.0722 * b
    a_chan = r - g
    b_chan = 0.5 * (r + g) - b

    return np.stack([l_chan, a_chan, b_chan], axis=2)


# ---------------------------------------------------------------------------
# Public API: generate reconstruction candidates
# ---------------------------------------------------------------------------

# Shared setup result type
_SetupResult = Tuple[
    np.ndarray, np.ndarray, np.ndarray,  # integral_sum, integral_sq, integral_count
    int, int,  # min_step, max_step
    Optional[int],  # resolution_hint
    int,  # offset_stride
]


def _setup_reconstruction(
    img: Image.Image,
    width: int,
    height: int,
    config: Config,
) -> Optional[_SetupResult]:
    """Shared setup for reconstruction-based grid detection.

    Converts image to perceptual color space, builds integral images,
    and determines the step size search range.

    Returns None if the image is too small or the search range is empty.
    """
    if width < 4 or height < 4:
        return None

    arr = np.array(img, dtype=np.uint8)
    alpha = arr[:, :, 3] if arr.shape[2] == 4 else np.ones((height, width), dtype=np.uint8) * 255
    mask = alpha > 0

    lab = _rgb_to_approx_lab(arr)
    integral_sum, integral_sq, integral_count = _build_integral_images(lab, mask)

    max_dim = max(width, height)
    min_dim = min(width, height)
    config_min = max(3, config.reconstruction_min_step)
    config_max = config.reconstruction_max_step

    min_step = max(config_min, max_dim // 128)
    max_step = min(min_dim // 2, config_max, max_dim // 4)

    if max_step < min_step:
        return None

    resolution_hint = config.resolution_hint
    offset_stride = 2 if max_step > 32 else 1

    return (
        integral_sum, integral_sq, integral_count,
        min_step, max_step,
        resolution_hint, offset_stride,
    )


def _coarse_search_and_refine(
    integral_sum: np.ndarray,
    integral_sq: np.ndarray,
    integral_count: np.ndarray,
    width: int,
    height: int,
    min_step: int,
    max_step: int,
    offset_stride: int,
    resolution_hint: Optional[int],
    max_candidates: int,
) -> List[Tuple[float, float, float, float]]:
    """Run coarse grid search + Nelder-Mead refinement on top results.

    Returns refined (error, step, ox, oy) tuples sorted by error,
    or empty list if no candidates found.
    """
    logger.debug(
        f"Reconstruction: coarse search step=[{min_step}..{max_step}], "
        f"offset_stride={offset_stride}"
    )
    coarse_results = _coarse_grid_search(
        integral_sum, integral_sq, integral_count,
        width, height, min_step, max_step,
        offset_stride=offset_stride,
        resolution_hint=resolution_hint,
    )

    if not coarse_results:
        return []

    n_refine = min(max(max_candidates, 3), len(coarse_results), 8)
    top_coarse = coarse_results[:n_refine]

    logger.debug(
        f"Reconstruction: top {n_refine} coarse candidates: "
        + ", ".join(f"step={s:.0f} err={e:.2f}" for e, s, _, _ in top_coarse)
    )

    refined: List[Tuple[float, float, float, float]] = []
    for error, step, ox, oy in top_coarse:
        r_error, r_step, r_ox, r_oy = _refine_grid_nelder_mead(
            integral_sum, integral_sq, integral_count,
            width, height, step, ox, oy,
        )
        refined.append((r_error, r_step, r_ox, r_oy))

    refined.sort(key=lambda x: x[0])
    return refined


def generate_reconstruction_step_estimates(
    img: Image.Image,
    width: int,
    height: int,
    config: Config,
    max_candidates: int = 3,
) -> List[Tuple[float, str]]:
    """Estimate optimal grid step sizes using reconstruction error minimization.

    Returns step size estimates (not cut lists) so the caller can use its own
    edge-snapped cut placement. This gives the best of both worlds:
    reconstruction's step finding + gradient-based boundary placement.

    Args:
        img: Original RGBA image (NOT quantized).
        width: Image width.
        height: Image height.
        config: Configuration options.
        max_candidates: Maximum step estimates to return.

    Returns:
        List of (step_size, source_label) tuples, sorted by reconstruction error.
    """
    setup = _setup_reconstruction(img, width, height, config)
    if setup is None:
        return []

    integral_sum, integral_sq, integral_count, min_step, max_step, resolution_hint, offset_stride = setup

    refined = _coarse_search_and_refine(
        integral_sum, integral_sq, integral_count,
        width, height, min_step, max_step,
        offset_stride, resolution_hint, max_candidates,
    )
    if not refined:
        return []

    # Deduplicate by rounded step (avoid near-identical candidates)
    results: List[Tuple[float, str]] = []
    seen_steps: set = set()

    for error, step, ox, oy in refined[:max_candidates * 2]:
        # Round to 0.5 to dedup near-identical steps
        step_key = round(step * 2) / 2
        if step_key in seen_steps:
            continue
        seen_steps.add(step_key)

        # Check resolution hint
        if resolution_hint is not None:
            cells_x = len(_make_uniform_cuts(step, 0.0, width)) - 1
            cells_y = len(_make_uniform_cuts(step, 0.0, height)) - 1
            if max(cells_x, cells_y) > resolution_hint:
                continue

        cells_x = len(_make_uniform_cuts(step, ox, width)) - 1
        cells_y = len(_make_uniform_cuts(step, oy, height)) - 1
        source = f"recon(s={step:.1f},{cells_x}x{cells_y})"

        logger.debug(f"Reconstruction step estimate: {source}, error={error:.4f}")
        results.append((step, source))

        if len(results) >= max_candidates:
            break

    return results


def generate_reconstruction_candidates(
    img: Image.Image,
    width: int,
    height: int,
    config: Config,
    max_candidates: int = 3,
) -> List[Tuple[List[int], List[int], float, str]]:
    """Generate grid candidates using reconstruction error minimization.

    Searches over step sizes and offsets to find the grid that best explains
    the observed image as a pixelated grid. Uses integral images for O(1)
    per-cell variance queries.

    The algorithm:
    1. Converts image to perceptual color space
    2. Builds integral images for fast variance computation
    3. Coarse search over integer step sizes and offsets
    4. Sub-pixel refinement via Nelder-Mead on top candidates
    5. Non-uniform local correction of grid boundaries
    6. Returns top candidates sorted by reconstruction error

    Args:
        img: Original RGBA image (NOT quantized).
        width: Image width.
        height: Image height.
        config: Configuration options.
        max_candidates: Maximum candidates to return.

    Returns:
        List of (col_cuts, row_cuts, step_size, source) candidate tuples.
    """
    setup = _setup_reconstruction(img, width, height, config)
    if setup is None:
        return []

    integral_sum, integral_sq, integral_count, min_step, max_step, resolution_hint, offset_stride = setup

    refined = _coarse_search_and_refine(
        integral_sum, integral_sq, integral_count,
        width, height, min_step, max_step,
        offset_stride, resolution_hint, max_candidates,
    )
    if not refined:
        return []

    # Take top candidates and apply phase 3 correction
    candidates: List[Tuple[List[int], List[int], float, str]] = []
    seen_grids: set = set()

    for error, step, ox, oy in refined[:max_candidates]:
        col_cuts = _make_uniform_cuts(step, ox, width)
        row_cuts = _make_uniform_cuts(step, oy, height)

        # Phase 3: Local non-uniform correction
        col_cuts = _local_grid_correction(
            integral_sum, integral_sq, integral_count,
            col_cuts, width,
            search_radius=max(1, min(int(step * 0.15), 3)),
            is_cols=True,
            other_cuts=row_cuts,
        )
        row_cuts = _local_grid_correction(
            integral_sum, integral_sq, integral_count,
            row_cuts, height,
            search_radius=max(1, min(int(step * 0.15), 3)),
            is_cols=False,
            other_cuts=col_cuts,
        )

        # Deduplicate
        grid_key = (tuple(col_cuts), tuple(row_cuts))
        if grid_key in seen_grids:
            continue
        seen_grids.add(grid_key)

        cells_x = len(col_cuts) - 1
        cells_y = len(row_cuts) - 1

        # Enforce resolution hint after local correction
        if resolution_hint is not None and max(cells_x, cells_y) > resolution_hint:
            logger.debug(
                f"Reconstruction: skipping corrected grid {cells_x}x{cells_y} "
                f"(exceeds hint={resolution_hint})"
            )
            continue

        source = f"recon(s={step:.1f},{cells_x}x{cells_y})"

        logger.debug(
            f"Reconstruction candidate: {source}, error={error:.2f}"
        )

        candidates.append((col_cuts, row_cuts, step, source))

    return candidates
